[toolchain]

[features]
seeds = false
skip-lint = false

round = "BoB8rikXuQDYqDet9YSpqYmXcCBYiRxPSeLW7iXz8VdG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
